### ISSUE TITLE
Can't compare to US GPA

### ISSUE THREAD

**Issue by rukeli** [sglavoie/uol-grades-calculator#1]
The GPA conversion to US is not quite right. 3.67 in the US system would be more like an A-. :)

**Comment by sglavoie** [comment]
Hi @rukeli, thanks for your feedback! :slightly_smiling_face: 

It's quite probable this little tool would need some tweaking. The actual calculations should be tested properly, but I may be using the wrong formula :grin:.

Do you have any suggestion on how the conversion should be happening? Right now, the average of all the grades is taken and then the "GPA" is calculated as follows for the US:

    average / 20 - 1

I have seen different ways of calculating this and the fact that the degree is being done with a university in the UK may affect the way the conversion should happen. If you have any idea on this, it's definitely welcome so I can make some adjustments :wink:.

**Comment by rukeli** [comment]
Hi @sglavoie!

This equation accommodates the conversions pretty well I think:

> if x ≥ 70, y = 4
if x < 70, y = 4x/70

Where **x** is the average cumulative raw score, and **y** is the approximate US GPA conversion.

Thanks for all your work on here, I'm finding it super helpful!

**Comment by sglavoie** [comment]
Thank you for your suggestion! I will have a better look into this tomorrow. It looks like it would be interesting to consider other measures as well such as:

* Unweighted vs weighted GPA;
* Cumulative GPA vs overall GPA;
* Regional systems like French, Spain, Dutch and Canadian...

I guess I will have to parameterize this, otherwise the output will become a bit cluttered :smile:.

**Comment by sglavoie** [comment]
@rukeli now I see where the mistake is after looking at the official 4.0 GPA scale :smile:. I'll be using the following to make the conversions, which should lead to the expected results:

![image](https://user-images.githubusercontent.com/32682903/94992379-38e4b500-054f-11eb-9bb2-98661934a308.png)

**Comment by sglavoie** [comment]
**FIXED**: Closing as the issue was resolved with the following commits:

* 1c6ec817b65d70fd7cbd427143ef3b2b9e972d0b
* fcaedfec1499c93f405ac8bd2ea0862a6e2f2d05
* 391459db07e8fd0167195fc9a81d4d0264a8fa61
* 340c99eea43ad26f40a532ac7444a343d3028e04
* 88934b333c1323e7bac4d6420ea9151e65f246e6

Now, the proper US GPA has been implemented along with the letter equivalence. Feel free to re-open this issue or another one if there's anything else :wink:.
